# Generated by Django 4.1 on 2022-10-19 20:28

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistas',
            name='precio_hora',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='Precio por hora de servicio'),
        ),
        migrations.AlterField(
            model_name='artistas',
            name='imagen',
            field=models.ImageField(upload_to=utils.models.path_image, verbose_name='Imagen'),
        ),
    ]
